### PR TITLE
Fix authorization for scenario execution delete

### LINKED ISSUE #257: 🐛 |  Cannot delete scenario execution
### Which part of our software stack is concerned by the problem ?

Chutney

### What happened?

When delete scenario execution via web interface, got a 403 which deconnects me right away.
This happens even if i have the `EXECUTE_WRITE` authorization.

### Steps to reproduce

Just try to delete a scenario execution.

### Relevant logs and/or screenshots/GIFs

Image

Image

### Version

4.0.0

### What browsers are you seeing the problem on ?

Chrome

### What OS did you use ?

Windows

### LINKED ISSUE #261: 🐛 |  Cannot see report values in embedded editor
### Which part of our software stack is concerned by the problem ?

Chutney

### What happened?

From report, try to clic on an action input see button.
The editor opens but there is no content;

I see this in console :

Image

### Version

4.0.0

### What browsers are you seeing the problem on ?

Chrome

### What OS did you use ?

Windows

### PR DESCRIPTION
**Pull request by boddissattva**
#### Issue Number
fixes #257
fixes #261

#### Describe the changes you've made

* Fix the authorization for scenario execution endpoint to `EXECUTION_WRITE`.
* Add test for checking `PreAuthorize` annotations.
* Clean up the `SecuredControllerSpringBootIntegrationTest` class.
* Fix Monaco editor import.

#### Checklist

- [x] Refer to issue(s) the PR solves
- [x] New java code is covered by tests
- [ ] Add screenshots or gifs of the new behavior, if applicable.
- [x] All new and existing tests pass
- [x] No git conflict

### CODE REVIEW

**Review by KarimGl — CHANGES_REQUESTED** [review]

File: chutney/server/src/main/java/fr/enedis/chutney/execution/api/ScenarioExecutionUiController.java [hunk 1]
```diff
@@ -104,7 +107,7 @@ public String executeScenarioWitRawContent(@RequestBody IdeaRequest ideaRequest,
     }
 
     @PreAuthorize("hasAuthority('EXECUTION_WRITE')")
-    @PostMapping(path = {"/api/ui/scenario/executionasync/v1/{scenarioId}/{env}", "/api/ui/scenario/executionasync/v1/{scenarioId}/{env}"}, consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
```
Comment (joelgaspard) [inline chutney/server/src/main/java/fr/enedis/chutney/execution/api/ScenarioExecutionUiController.java]: il n'y a plus le path executionasync ?
